task: 'full' # brauchen wird
im_size: [[192,192], [96, 96]] # brauchen wir
num_input: 1 # brauchen wir # normal: 1 --> gibt an, wie viele Bildkanäle geladen werden --> 1: Graubild, 3: RGB-Bild
#num_output: [1, 3] 
num_keypoint: 32 # brauchen wir normal 10
growth_rate: [24, 24, 64] # brauchen wir
blk_cfg_enc: [[2, 3, 4], [4, 3, 2]] # brauchen wir
#blk_cfg_dec: [4, 3]
#blk_cfg_cvt: [4, 4, 4]
drop_rate: 0.2 # brauchen wir default=0, 0.2 bedeutet, dass jedes Neuron mit einer Warscheinlichkeit von 20% augeschalten wird. Bei 1 wären alle ausgeschalten
lr: 0.001 # brauchen wir # 0.001
wd: [0.00005] # 0.00005 # Reguliert Gewichte reduziert Overfitting verändert VerlsustfunktionJed größer desteo stärker der Einfluss
lr_anne: 'repeat' # brauchen wir

batch_size: 16 #16 # brauchen wir
ep_train: 24 #24 # brauchen wir
#bootstrap: 0.3
concentrate: -60 # brauchen wir ums höher umso schneller wird LossC zu 0  # alter Wert -20
inside: 50 # 50,250
sigma_kp: [1.0, 2.5] # brauchen wir sigma_kp: [1.0, 2.5]
#a_dist: -200

obj_class: [0, 1] # orginal: [0,1,2]
threshold: 80
#motion_vec: [True, True, True, True, False, False]
mean: 0.41 # brauchen wir mean: 0.41
std: 0.26 # brauchen wir std: 0.26
#cam_clip: [0.05, 0.49]


# texture: [0, 40]
# hue: [0, 0]
# saturation: [1, 1]
# brightness: [0.4, 1.3]
# contrast: [0.3, 1.7]
# sharp: [0.5, 1.5]
# gamma: [1, 1]
# blur: [0.1, 0.5]
# noise: [8, 40]
# bg: 1

gpu: True
dir_base: 'result/dataset_2_2023_05_04' # Ordner, in welchem die results gespeichert werden --> Ändern ist unpraktisch
dir_dataset: 'dataset/dataset_2_2023_05_04' # Ordner in welchem die traingsbilder und testbilder liegen

